# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abd31c0560ae219c5c46655e915e3f1c69e51fd131c2f216dbfd3c7f07b9a9e2dc07be4eaeffb8cf88f5619fdde5a0423b4a2897131b8dcb88ee82519a2318ff

test:
  secret_key_base: 0e1a914c6aee4c676e06c514fb9b9bebfc20989b859daf51f2e0204eb0bcc684eac4c04351a724664bf109addcc00a4b8bc56a7c650b942391054d83c605ee08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
